name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Check code style
        id: lint
        run: |
          npx prettier ./src/ --check || echo 'lint-failed'

  remark:
    runs-on: ubuntu-latest
    needs: lint
    if: steps.lint.outputs.lint-failed != ''
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Fix code style
        run: npx prettier ./src/ --write

  build:
    runs-on: ubuntu-latest
    needs: [ lint, remark ]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
