name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      lint-failed: ${{ steps.lint.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Check code style
        id: lint
        run: |
          npx prettier ./src/ --check
        continue-on-error: true
      - name: Set output
        id: output
        run: echo "result=$(exho $?)" >> $GITHUB_ENV

  remark:
    runs-on: ubuntu-latest
    needs: lint
    if: lint.outputs.lint-failed != '0'
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Fix code style
        run: npx prettier ./src/ --write

  build:
    runs-on: ubuntu-latest
    needs: [ lint, remark ]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
