name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      lint-failed: ${{ steps.output.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Check code style
        id: lint
        run: |
          npx prettier ./src/ --check
        continue-on-error: true
      - name: Set output
        id: output
        run: echo "result=$(echo $?)" >> $GITHUB_ENV

  remark:
    runs-on: ubuntu-latest
    needs: lint
    if: needs.lint.outputs.lint-failed != '0'
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Fix code style
        run: npx prettier ./src/ --write

  build-true:
    runs-on: ubuntu-latest
    needs: lint
    if: needs.lint.outputs.lint-failed == '0'
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t ghcr.io/d1pper22d1p/hahahaha-my-comment/students-node-330:latest ./

      - name: Login to github registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker image
        run: docker push ghcr.io/d1pper22d1p/hahahaha-my-comment/students-node-330:latest  

  build-false:
    runs-on: ubuntu-latest
    needs: [lint, remark]
    if: needs.lint.outputs.lint-failed != '0'
    steps:
      - uses: actions/checkout@v4
      - name: Send Telegram message for lint errors
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAMBOT_TOKEN }}/sendMessage" \
          -d "chat_id=-4587543996&text=Build%20failed%20due%20to%20linting%20errors."
